analyze_resume_task:
    description: >
        Read the resume for the path: {resume_path}. Analyze the candidate's resume and provide a detailed report on their skills, experience, and potential fit for the job.
    expected_output: >
        A comprehensive analysis of the candidate's qualifications, experience. Give specific highlight and recommendation to improve the resume.

analyze_job_requirements_task:
    description: >
        Read the job description for the path: {job_description_path}. Analyze the job requirements and provide insights on the skills and experience needed for the role.
    expected_output: >
        A detailed analysis of the job requirements, including key skills, qualifications, and experience needed for the role.  At the end of the result, please also list all the keywords regarding the job requirement in bullet points.

google_job_requirements_task:
    description: >
        Search for similar job descriptions online based on the job requirements from {job_description_path}. Provide additional insights on the skills and experience needed for the role based on the search results.
    expected_output: >
        Additional insights on the skills and experience needed for the role based on similar job descriptions found online. Provide recommendations on how the candidate can enhance their resume to better align with the job requirements.

compare_resume_and_job_requirements_task:
    description: >
        Compare the candidate's resume from {resume_path} and the job description from {job_description_path}, provide insights on the match between the candidate's skills and the job requirements.
    expected_output: >
        An evaluation of how well the candidate's skills and experience match the job requirements. Provide recommendations on how to improve the match between the candidate's resume and the job requirements. At the end of the result, please also list the appreciate number of keywords regarding the job requirement in bullet points, and the number of keywords that the candidate has in their resume. Give some tips for the job application and interview process for example how to highlight the skills and experience that match the job requirements.

interview_preparation_task:
    description: >
        Prepare the candidate for a job interview based on the job requirements from {job_description_path}. Provide guidance on how to highlight their skills and experience during the interview and answer questions effectively.
    expected_output: >
        Tips and strategies for preparing for a job interview based on the job requirements. Provide guidance on how to highlight key skills and experience during the interview, answer questions effectively, and demonstrate their fit for the job role. At the end of the result, please also list the appreciate number of keywords regarding the job requirement in bullet points, and the number of keywords that the candidate has in their resume. Give some tips for the job application and interview process for example how to highlight the skills and experience that match the job requirements.

future_recommendations_task:
    description: >
        Compare the candidate's resume from {resume_path} and the job description from {job_description_path}, provide recommendations on how the candidate can improve their resume to better match the job requirements. You can recommend specific areas for improvement and suggest ways to highlight key skills and experience or any certifications that the candidate can obtain to enhance their resume.
    expected_output: >
        Specific recommendations on how the candidate can enhance their resume to better align with the job requirements. Provide guidance on areas for improvement and suggestions for highlighting key skills and experience. Recommend any certifications or training programs that the candidate can pursue to enhance their qualifications with link attached.

generate_cover_letter_task:
    description: >
        Compare the candidate's resume from {resume_path} and the job description from {job_description_path}, craft a compelling cover letter that highlights the candidate's skills and experience and demonstrates their fit for the job. The cover letter should be tailored to the specific job requirements and showcase the candidate's qualifications.
    expected_output: >
        A well-crafted cover letter that highlights the candidate's skills and experience, demonstrates their fit for the job, and aligns with the job requirements. The cover letter should be tailored to the specific job role and showcase the candidate's qualifications.